name: Imprimir Hola Mundo

on:
  push:
    branches:
      - main

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Imprimir Hola Mundo
        run: echo "Hola Mundo"
